---
- name: Install Jenkins on Ubuntu
  hosts: localhost
  become: true

  tasks:
    - name: Add Jenkins APT key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key

    - name: Add Jenkins APT repository
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Create /etc/sudoers.d/ directory
      file:
        path: /etc/sudoers.d/
        state: directory
        mode: 0755
      become: true

    - name: Add Jenkins to sudoers
      lineinfile:
        path: /etc/sudoers.d/jenkins
        line: "jenkins ALL=(ALL) NOPASSWD:ALL"
        create: yes
      become: true

    - name: Create docker group
      group:
        name: docker
        state: present
      become: true

    - name: Add Ubuntu user to Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
      become: true

    - name: Restart Jenkins service
      service:
        name: jenkins
        state: restarted
        
    - name: Copy Jenkins password file
      command: "cp /var/lib/jenkins/secrets/initialAdminPassword /home/ubuntu/Jpassword.txt"
      args:
        creates: /home/ubuntu/Jpassword.txt
      become: true
